"""Creación inicial de tablas

Revision ID: df99f31098bf
Revises: 
Create Date: 2025-05-19 14:17:41.481105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df99f31098bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destino', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('viaje')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viaje',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origen', sa.VARCHAR(), nullable=False),
    sa.Column('destino', sa.VARCHAR(), nullable=False),
    sa.Column('fecha', sa.VARCHAR(), nullable=False),
    sa.Column('pasajero', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('viajes')
    # ### end Alembic commands ###
